name: Test publish package to TestPyPI

on:
  # Allows manually running this workflow from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: Pre-check
      run: |
        make pre-test-publish-check

  release-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: Build test release distributions
      run: |
        python -m pip install flit
        flit build

    - name: Upload test distributions
      uses: actions/upload-artifact@v4
      with:
        name: test-release-dists
        path: dist/

  publish-to-testpypi:
    runs-on: ubuntu-latest
    needs:
      - test-release-build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see:
    #   https://docs.pypi.org/trusted-publishers/adding-a-publisher/
    #   https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    # This is also relevant, though the "on" condition is different:
    #   https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
    environment:
      name: testpypi
      url: https://test.pypi.org/p/ocsf-schema-compiler

    steps:
      - name: Retrieve test release distributions
        uses: actions/download-artifact@v5
        with:
          name: test-release-dists
          path: dist/

      - name: Publish test release distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: https://test.pypi.org/legacy/
